### ISSUE TITLE
BDD-Anomaly dataset

### ISSUE THREAD

**Issue by Markovcom** [hendrycks/anomaly-seg#1]
Hello, thank you for your work, where can i get the BDD-Anomaly dataset?

**Comment by xksteven** [comment]
Hello, the BDD dataset can be downloaded from: https://bdd-data.berkeley.edu/portal.html

The file "create_dataset.py" contains the preprocessing we used to convert BDD into the appropriate format.  

Let me know if you have any other issues.

**Comment by LT1st** [comment]
> Hello, the BDD dataset can be downloaded from: https://bdd-data.berkeley.edu/portal.html
> 
> The file "create_dataset.py" contains the preprocessing we used to convert BDD into the appropriate format.
> 
> Let me know if you have any other issues.

how can u find this data set in "profile"??????????????
show me the right one pls
