### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by gongshichina** [hendrycks/anomaly-seg#12]
Could you please share your pretrained segmentation model on BDD100K? I found your released model in Google Drive is the one for StreetHzards.

**Comment by gedoensmax** [comment]
If you are on it i would very much welcome th eplaces 365 model too.

**Comment by hendrycks** [comment]
We couoldn't find the BDD100K model, but Places 365 models are here: https://github.com/CSAILVision/places365

**Comment by gedoensmax** [comment]
Ok so for imagenet most probably just the torchvision model with pretrained set to True right ?

**Comment by hendrycks** [comment]
Yes
