### ISSUE TITLE
Couldn't match the BDD100K file paths

### ISSUE THREAD

**Issue by zjysteven** [hendrycks/anomaly-seg#14]
Hi,

Thanks for making all the codes public, which is very helpful. Yet, I'm just having difficulty preparing the BDD100K data. 

https://github.com/hendrycks/anomaly-seg/blob/c7cdd0a36c0aa142a99dfa3ac43d62f55e984897/create_dataset.py#L152-L155

Specifically, in `create_dataset.py`, I don't see what is the `seg` folder in line 153, and also couldn't find where to download `train_labels`. More clearly, I downloaded the `100K Images` and `Segmentation` files from the BDD100K website, unzipped them, and now I have a folder whose structure is as follows:

```
bdd100k
├── images
│   ├── 100k
│   │   ├── test
│   │   ├── train
│   │   ├── val
├── labels
│   ├── sem_seg
│   │   ├── colormaps
│   │   ├── masks
│   │   ├── polygons
```

As you can see, no subfolders correspond to `train_labels/train`. I would appreciate it if more clear instructions can be given, e.g., what is the expected folder structure, or exactly where should I download the `train_labels`? 

Thanks!

**Comment by xksteven** [comment]
I'll will look into this by the weekend and update this issue if I have a chance to get to it sooner. Thanks for pointing it out! :)
Worse case I'll just reshare our processed labels directly. We wanted to limit how much was shared from BDD as they want users to sign up and go through their system.

**Comment by zjysteven** [comment]
@xksteven Thanks! Looking forward to updates.

**Comment by xksteven** [comment]
@zjysteven I added a file specific for the BDD100K.  I believe that the images are from the 10K portion of BDD as the BDD100K images many do not have labeled annotations (at least at the time we did this work).  

I'll add to the README but you can pattern match these label ids to the image ids to match labels to images.  This should hopefully address all of your concerns but let me know if you have any remaining issues or questions.
