### ISSUE TITLE
Some points to confirm about the CAOS benchmark

### ISSUE THREAD

**Issue by huanhuan-HUST** [hendrycks/anomaly-seg#17]
I'm sorry I don't know how to reopen again, so I created another issue.
Thank you for your answer, but I still have some points to confirm.
1.For StreetHazards dataset, there are a total of 14 classes(0:unlabeled,1:building,2:fence,3:other,...13:anomaly).The label in the label file is from 1 to 14, minus 1 corresponds to 0-13 here. Unlabeled Corresponding background.Use 0-12 for training(a total of 13 categories), including 0(0:unlabeled) and 3(3:other), and use 0-13 for testing(a total of 14 categories), right?
2.For BDD-anomaly dataset, there are a total of 20 classes (0:road,1:sidewalk,...18:bicycle,255:other). Use 0-15 and 255(other) for training(a total of 17 categories), only does not contain 16-18, and use 0-18 and 255 for testing(a total of 20 categories), right?
Thank you very much and looking forward to your reply.

**Comment by xksteven** [comment]
Both points are correct :)
I'll leave open this issue for a day or two in case you have a quick follow-up question. There should be a button on the side that let's you reopen a closed issue.

**Comment by xksteven** [comment]
Please see here for how we tested our [OOD methods](https://github.com/hendrycks/anomaly-seg/blob/master/eval_ood.py#L254) in case you want to add a different one to it.

**Comment by huanhuan-HUST** [comment]
Thank you very much!

**Comment by xksteven** [comment]
I'll just add an additional comment just to be extra clear about when we say to use all of the labels during testing. The model can only output the training labels because that's what it was trained on. However we can evaluate how confident the model is on the predictions for the anomalous class or classes during testing. 
Note that we did not include any of the anomalies in the training set. In our set up the model does not have an "anomalous" class or category during training.

Have fun!

**Comment by kehuantiantang** [comment]
Dear  xksteven:
Thank you so much for your work.
I still confuse about detecting the anomalous class. As you said that we can evaluate how confident the model is on the predictions for the anomalous class or classes during testing,  which can evalue the performance according to the evaluation metrics `auroc, aupr`. However, `auroc, aupr` calculated by adjusting the threshold of confidence score. 
If we want to visualze the final anomaly segmentation result like 'Figure 4, prediction result',  we should define a `certain threshold` (for example,  0.5 for binary classification), is it means calculate the threshold value in test and apply the same value for prediction ?
![image](https://user-images.githubusercontent.com/5328587/141403263-e796aca5-879c-48d5-ad95-f0b3e841de74.png)

Also, if we select the threshold Θ to split normal/anomaly, how to classify classes in in-distribution class ? Argmax ?   
Look forward to your reply, thank you so much.
