### ISSUE TITLE
Two more stages in resnet

### ISSUE THREAD

**Issue by wiseManCanSeeIt** [hendrycks/anomaly-seg#18]
Hello!
I have a little question about the resnet arch implemented by yourself. I notice that there are two more stages before resnet layer_1 compared to the official code released in torchvision.
I wanna know why there are two more stages😂
Thanks for your time!

**Comment by huanhuan-HUST** [comment]
The official resent is a 7*7 convolutional layer before  resnet layer_1. The author uses three 3*3 convolutions instead to reduce the amount of parameters.

**Comment by wiseManCanSeeIt** [comment]
> The official resent is a 7x7 convolutional layer before resnet layer_1. The author uses three 3x3 convolutions instead to reduce the amount of parameters.

Really thanks for your help! It's my mistake.
