### ISSUE TITLE
how about the class define?

### ISSUE THREAD

**Issue by xueyoo** [hendrycks/anomaly-seg#19]
there are 17 class defined in defaults.py  and the anomaly class is 13,
the comment in create_dataset.py  has defined 13 class, but found some color in image which under in folder seg/color_labels,  but not in create_dataset.py's comment

so how about the 17 class names and their color defines?
does the anomaly class data existed in training stage?

**Comment by xksteven** [comment]
The labels present in the seg/ are for the BDD anomaly dataset. We provided the preprocessed labels for convenience. 

Does that answer your question?

**Comment by xueyoo** [comment]
yes, thanks
