### ISSUE TITLE
About StreetHazars Dataset

### ISSUE THREAD

**Issue by Markovcom** [hendrycks/anomaly-seg#2]
Hello, there are 250 anomaly types  in this dataset introduced by your paper. What are these anomaly types specifically?

**Comment by xksteven** [comment]
We sourced the anomalies from semantic ShapeNet and Model Bank Library. It includes but is not limited to vehicles (such as military vehicles, ships, planes, construction vehicles), animals (such as ape, zebra, kangaroo, etc), furniture, electronic objects (such as mouse, keyboard, hair dryer), and other miscellaneous object types such as a rocket and a space capsule. 

We did ensure that there was no overlap between the training classes and the anomalous objects.

**Comment by Markovcom** [comment]
OK, thank you very much.
