### ISSUE TITLE
how to show the anomaly scores?

### ISSUE THREAD

**Issue by xueyoo** [hendrycks/anomaly-seg#20]
![1](https://user-images.githubusercontent.com/8454381/130170335-39c1e26f-6fb0-426b-85c9-93b7ae3da521.png)

**Comment by hendrycks** [comment]
This isn't a formed question.

**Comment by xksteven** [comment]
We describe how to generate the anomaly scores in the README

    # To evaluate the model on out of distribution test set
    python3 eval_ood.py DATASET.list_val ./data/test.odgt

Finally to actually plot it make sure the visualize flag is set to true in the configuration file.  See this [line](https://github.com/hendrycks/anomaly-seg/blob/master/eval_ood.py#L174) for where it gets called.
