### ISSUE TITLE
Evaluation based on each image vs entire dataset 

### ISSUE THREAD

**Issue by tianyu0207** [hendrycks/anomaly-seg#21]
Hi, 

Congrats on the great paper. 

I checked your evaluation method and found that the results based on the mean of fprs over all images are better than the results based on flattened scores and labels of the entire dataset. Why do you use image-wise results instead of the entire dataset to calculate the fpr. 

Thanks.

**Comment by hendrycks** [comment]
I do not think we had a particular reason to aggregate across images. Both seem valid.
