### ISSUE TITLE
About metrics of AUPR, AUROC, and FPR95

### ISSUE THREAD

**Issue by JackyLin7414** [hendrycks/anomaly-seg#25]
Hi, @xksteven 

I am confuse about the metrics of CAOS benchmark.
Are AUPR, AUROC and FPR95 pixel-level metrics?

Thank you
Jacky

**Comment by xksteven** [comment]
For CAOS they are pixel level see the implementation details [here](https://github.com/hendrycks/anomaly-seg/blob/master/anom_utils.py#L106-L113).  It takes in the pixel level segmentation map (or image) and the ground truth pixel level anomaly map.  Then computes the scores given the two maps.
