### ISSUE TITLE
Broken link to BDD-Anomaly dataset

### ISSUE THREAD

**Issue by matteosodano** [hendrycks/anomaly-seg#27]
Hi everyone, 
thanks for your work. I'm interested in downloading the datasets for academic purposes. However, github points to a non-existing page when clicking on the link of the BDD-Anomaly dataset. Where can I find the train/val/test images? 
Thank you.

**Comment by xksteven** [comment]
Thanks for reporting this.  We've fixed the first link.  Without having https in front it seems as though Github interprets these links as relative links to the code.  I don't believe this used to be the case but we've gone ahead and fixed it.
