### ISSUE TITLE
Question about CAOS dataset training

### ISSUE THREAD

**Issue by matteosodano** [hendrycks/anomaly-seg#29]
Hello,
thanks for your work. I wanted to ask some simple questions about the models you trained for the CAOS benchmark. 

- Did you train two different models for BDDAnomaly and StreetHazards?
- If you trained a single model, how did you merge the training data (in particular, how did you match the classes of the two datasets)?

Thanks.

**Comment by matteosodano** [comment]
Ah, perfect. Thanks!

One further question: which model corresponds to the pretrained weights you shared? Is the code available in the `semantic-segmentation` submodule?

**Comment by xksteven** [comment]
The model shared was for the BDD dataset.
Yup the code we used is directly linked to the commit from the semantic-segmentation module.  We worked to update our codebase to run with a newer versions of the submodule but no longer have time to keep in sync with any changes made to the submodule.

**Comment by matteosodano** [comment]
Yep, I meant which encoder and which decoder are the ones you used for those weights? I saw there are many available in the submodule, and the file names of the `.pth` don't point to one in particular

**Comment by xksteven** [comment]
We do list it in the paper which architecture we used: ResNet101dilated + PPM_deepsup

**Comment by matteosodano** [comment]
Right. Thanks again!

**Comment by matteosodano** [comment]
Hi, sorry but I have another question and can't seem to figure it out.

On the paper, you write
```We source BDD-Anomaly from BDD100K. [...] There are 18 original classes. We choose motorcycle, train, and bicycle as anomalous objects classes and remove all images with these objects from the training and validation sets.```

The original classes should be 19. But anyways, this should lead to a network that segments 15 classes (or 16 if we consider 19 original ones). However, the pretrained weights you shared in the GDrive folder are for a RN101D+PPMDS that segments only 13 classes:

```
RuntimeError: Error(s) in loading state_dict for PPMDeepsup:
	size mismatch for conv_last.4.weight: copying a param with shape torch.Size([13, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([16, 512, 1, 1]).
	size mismatch for conv_last.4.bias: copying a param with shape torch.Size([13]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for conv_last_deepsup.weight: copying a param with shape torch.Size([13, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([16, 512, 1, 1]).
	size mismatch for conv_last_deepsup.bias: copying a param with shape torch.Size([13]) from checkpoint, the shape in current model is torch.Size([16]).
```

Did I get something wrong? Which classes are you using?

Thanks again for the prompt support!

**Comment by xksteven** [comment]
I'll double check the model weights. As maybe we had uploaded the weights for CAOS model. If so I'll double check if we have the pretrained weights for BDD still. 

The code is currently set up to run with the defaults for CAOS dataset so you might have to change a few things from the defaults.py file. 

Also you're correct about the typo it's 19 classes, 20 if you include the unlabeled pixels.

**Comment by xksteven** [comment]
Okay I just confirmed.  I was previously incorrect and the model uploaded was for the CAOS dataset which is why it's of size 13.

**Comment by xksteven** [comment]
I can upload the BDD model weights too and reupload the model_weights folder to make it more clear which weights are for which model.

Unfortunately I cannot confirm if the old BDD weights I have saved are currently from a resnet50 or resnet101 so if I upload it could you test it out for me?

**Comment by matteosodano** [comment]
Sure, I can give it a look. Let me know when you upload them.

**Comment by xksteven** [comment]
Updated the model weights link posted here as well: https://drive.google.com/file/d/1HIQAhX8WIokZpymslUPDmpbUWdYEKEQ3/view?usp=share_link

**Comment by matteosodano** [comment]
Model weights for BDD are also referred to ResNet101dilated encoder with PPM deepsup decoder!
Thanks for sharing them.
