### ISSUE TITLE
BDD dataset training yaml

### ISSUE THREAD

**Issue by YingdaXia** [hendrycks/anomaly-seg#4]
Hello authors,

Thank you for your hard work! My question is that what's the training hyper parameters for BDD dataset? Is it the same as Street Hazards?

Thanks,
Yingda

**Comment by xksteven** [comment]
We kept both hyperparameters the same on BDD and StreetHazards.  We used the defaults from ADE20K.  

To get improved performance using a batchsize larger than 2 helps out significantly. We also found that UPerNet50 performed better than the dilated ResNet50 + PPM_deepsup backbone although this effect was marginal.
