### ISSUE TITLE
working on google colab

### ISSUE THREAD

**Issue by julienguegan** [hendrycks/anomaly-seg#9]
Does the code work on google colab ? 

Iha ve this error "KeyError: Caught KeyError in DataLoader worker process 0." when calling **train(segmentation_module, iterator_train, optimizers, history, epoch+1, cfg)** after running the command `python3 train.py --gpu 1`  ...

[https://colab.research.google.com/drive/1mzgBaWtCpfbojTqBIyYqCMAgYCicZKq8?usp=sharing
](url)

**Comment by hendrycks** [comment]
We have not tried using this on Google Colab.

**Comment by julienguegan** [comment]
Note that I follow the recommanded step in the README and actually it may come from `python create_dataset.py` I have **'FileNotFoundError: [Errno 2] No such file or directory: 'data/train/images/test/'**  ... Could you give some more indications on how the repositories should be ?

**Comment by hendrycks** [comment]
@xksteven

**Comment by xksteven** [comment]
I updated the repo.  The error should be gone now.  Pull it again or download the updated create_dataset.py and defaults file.  Thanks for the bug report.

@julienguegan

**Comment by julienguegan** [comment]
Thanks for the update @xksteven . The previous error have disappeared but I think there is still something missing because I can't make the command `python train.py` works... I had to add **feed_dict = feed_dict[0]** in line 32 of models.py because I had a list and not a dictionnary but then I have "Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same". You can check [](https://colab.research.google.com/drive/1mzgBaWtCpfbojTqBIyYqCMAgYCicZKq8?usp=sharing) if you have time

PS : I also noted one minor error in eval_ood.py : `in_scores = - conf[np.logical_not(out_label))]` **line 51**, there is one parenthesis too many

**Comment by xksteven** [comment]
train.py needs to be modified as per this [issue](https://github.com/hendrycks/anomaly-seg/issues/3#issuecomment-574846086) to run on a single GPU.

to run on a single GPU it's 

    train.py --gpu 0 

as opposed to train.py --gpu 1 .

I've also uploaded the pretrained models that can be found [here](https://drive.google.com/file/d/1gaaBMY42HiQ9SBQ9N8Rv258HuCvVox8u/view?usp=sharing)

Finally to run the eval_ood.py if using the default config/ade20k-resnet50dilated-ppm_deepsup.yaml and the model I've uploaded the num_classes parameter has to be changed to 13.

I've also updated the README as well to reflect these changes
